### ISSUE TITLE
Depend on conduit?

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/rio#1]
Some of the support code pulled out of Stack provides conduit helper functions. Should we keep a dependency on conduit in rio, or rather drop it?

**Comment by kerscher** [comment]
I say for executables a dependency, and for libraries and tests not. Not every library needs to deal with streaming data.

**Comment by snoyberg** [comment]
Answer: no. I'll design conduit to be compatible with rio instead, so you can just:

```haskell
import RIO
import Conduit
```

**Comment by roman** [comment]
Is the trend on libraries towards not using the `Control` or `Data` prefixes anymore? I understand that currently `conduit` has an import of `Data.Conduit` correct?

**Comment by mgsloan** [comment]
@roman The distinction between control and data seems tenuous to me.  It's easier to remember imports if it's directly based on the package name + sub thing.
