### ISSUE TITLE
Why is `logFuncL` a lens?

### ISSUE THREAD

**Issue by fumieval** [commercialhaskell/rio#102]
As far as I can see from the source code, it's only used as a getter; if it were just a function, it would be easier to define. Is there any plan to make use of the setter, like modifying the log function through `magnify`?

**Comment by snoyberg** [comment]
It's not currently used by the library, but:

1. It could be, such as by providing a `silently` function to turn off logging for a subset of code
2. Using the setter part of the lens can already happen outside of the library

**Comment by fumieval** [comment]
I see, thanks for explanation.
