### ISSUE TITLE
Qualified imports proposal

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/rio#12]
I propose we take the braindead simple approach of:

```haskell
import Rio
import qualified Rio.Exe as Exe
import qualified Rio.List as List
import qualified Rio.Vector as Vector
import qualified Rio.Text as Text
```
(The rule being `Rio.<foo>` is qualified as `<foo>`).

Where `Rio` exports in the namespace the names of types, and generic functions like `fmap` and `(<>)`, but functions/values are qualified. Lazy versions of things can have an alias like `LazyText` or unboxed things like `UnboxedVector`.

I can add support to Intero that will for example just automatically import `import qualified Rio.Text as Text` to your imports list if you write e.g.

``` haskell
main = writeUtf8 (Text.intercalate ", " xs)
```

So while the list grows, if it's automatically managed, it comes for free. So you wouldn't actually write your own import lists, the editor would do it.

**Comment by snoyberg** [comment]
Personally, I'd rather have the shorter qualified names we usually use today, e.g. `B` for `ByteString`, `BL` for lazy `ByteString`, `T` for `Text`, etc.

Also: I've been using `RIO` upper case for module names; is that a problem?

**Comment by NorfairKing** [comment]
I also prefer:

```
import qualified Data.ByteString as SB
import qualified Data.ByteString.Char8 as SB8
import qualified Data.ByteString.Lazy as LB
import qualified Data.ByteString.Lazy.Char8 as LB8
```

**Comment by chrisdone** [comment]
> Also: I've been using RIO upper case for module names; is that a problem?

From a tooling perspective it shouldn't matter; I'll just be typing lowercase from editor support anyway.

> Personally, I'd rather have the shorter qualified names we usually use today, e.g. B for ByteString, BL for lazy ByteString, T for Text, etc.

I think that whole `B`/`L` thing is a bit incomplete and everybody (just look at @NorfairKing's --  and elsewhere within our own team) just has slightly different versions of everything and muddles along. It trips me up when people use different things.  Here are some things that I personally regularly find conflicting or otherwise I just randomly pick something.

```haskell
Data.Map  (strict/lazy), Data.HashMap.Strict, Data.IntMap -- as M
Data.Text, Data.Tree, Data.Trie -- as T
Data.Text.Lazy as LT?
Data.Vector, Data.Vector.Unboxed as V, UV, SV, MV? UMV? etc.?
Data.ByteString, Data.Sequence, Data.Set, Data.HashSet, Data.IntSet as S  (Data.Store -- ??)
Data.ByteString.Lazy, Data.List as L?
Data.BloomFilter -- BF?
```

(This doesn't consider things like `Data.Attoparsec.ByteString` and `Text.Parsec`.)

If you name one module a single letter it's just inconsistent and a bit random. There is a long-form scheme:

```haskell
import Data.Map as Map
import Data.HashMap.Strict as HashMap
import Data.Map.Lazy as LazyMap
import Data.Text as Text
import Data.Text.Lazy as LazyText
import Data.Vector as Vector
import Data.Vector.Unboxed as UnboxedVector
import Data.ByteString as ByteString (or perhaps Bytes)
import Data.ByteString as LazyByteString (or perhaps Bytes)
import Data.Sequence as Sequence
import Data.List as List
import Data.Set as Set
import Data.HashSet as HashSet
import Data.Store as Store
```

But things like `ByteString` and `Sequence` and `HashSet` are pretty long to type. 

In any case - if we write a bit of editor support for it then it won't matter too much. For example, in my personal emacs, I type `C-i` and hit `d.b.l` and it adds

```haskell
import Data.ByteString (ByteString)
import qualified Data.ByteString.Lazy as L
```

in my module automatically. Similarly, if we want that strict ByteString is imported as `SB`, we need only have our team request `ByteString` (via a keybinding) and it'll import for them with the qualification that we want to standardise and they'll just move ahead and use that one.

Maybe we can just make a little table in our README saying how things ought to be imported too, so that we as a team can refer to it.

**Comment by snoyberg** [comment]
I definitely want to go for consistency here, it constantly trips me up that I don't know of `M` is `MVar` or `Map`, or whether I need to reach for `LBS` or `L` or `BL`. Having a table in the readme, or including a comment in each module explaining its expected qualified import name, is vital. I think we just need to standardize on something.

I know that my vote goes towards `B` and `T` for strict ByteString and Text, respectively. I'm fine giving longer names for the lazy variants (I particularly dislike `L` for lazy ByteString these days, even though it's an old semi-standard). And I like `Map` and `Set`. In fact, I'm even on board with `HashMap` and `HashSet`, though that is getting towards my limit.

For vector: I'd consider `V` as a qualified name for `Data.Vector.Generic`, and make `VB`, `VU`, and `VS` work for the boxed, unboxed, and storable modules. We can then include `BVector`, `UVector`, and `SVector` type synonyms in the `RIO` module itself. Or alternatively `BoxedVector`, `UnboxedVector`, and `StorableVector` if desired, but I think the one letter is sufficient here.

One thing I think worth considering is whether we're assuming any particular tooling being used by developers using `rio`. I strongly suspect we will regularly end up with teams with diverse editor choices, and shouldn't pin ourselves down to depending on the editor to make coding pleasant.

**Comment by snoyberg** [comment]
Whatever we end up deciding here, a "nice to have": a lint tool (maybe just rules to hlint) that looks at imports and warns you if you've deviated from `rio` recommendations. It can tell you if you've:

* Imported `Data.Text` instead of `RIO.Text`
* Imported with the wrong qualified name

**Comment by steshaw** [comment]
Wouldn't it be great if you could import a Prelude-like module that imported _namespaces_ rather than everything at the top level? In Yesod projects, we typically have an `Import` module that pollutes the global namespace with everything that could be important. This is very convenient but you often run into trouble when using `-Wall`, since you get shadowing of variable warnings quite a lot (another GHC extension could probably solve that by allowing you to shadow variables _on purpose_ — I've heard @pigworker lament about such things in a few talks).

What do you guys think of a GHC extension would would allow exporting namespaces so that you can "standardise" on short qualified names for modules? Short modules names is something that I notice when I look at [Go](https://golang.org/) code. I want it. Consistently and ubiquitously.

**Comment by snoyberg** [comment]
That's something I'd absolutely love. I'm trying to make plans in this
initiative for GHC as it exists today, but if a future GHC has this
feature, I would absolutely use it.

**Comment by snoyberg** [comment]
Thanks to @roman: here's an example of an hlint config for enforcing qualified import naming: https://gist.github.com/roman/2f6855d747457ce4c22cd64f5dc2996b#file-lib-hsfiles-L187-L200

**Comment by PierreR** [comment]
FWIW if I show some Haskell code to people that are not well aware about Haskell own idiosyncrasies, I will lose them very quickly as soon as they see `T.intercalate` while I keep them happy with `Text.intercalate`.

Personally I quite don't understand why the first might be better than the more explicit second. Recently @Gabriel439 in most recent code favors a complete qualified name. I believe this is a bit over the top but really short letters like `M`, `T`, `LT` , `V` looks quite nuts as soon as you take the habit to use longer form.

**Comment by chrisdone** [comment]
@Gabriel439 

I'm in agreement that full qualification is best; it's clear to read and don't require looking up module names. However, I also think traditional module names like `Data.ByteString` are gratuitously long and it could just be `Bytes`; I might even suspect that ridiculously long module names of Haskell contributes to people aliasing their imports. That's one thing we're solving with `RIO` to make it `RIO.ByteString` or so; and lets us possibly assume everything `Rio.X` is qualified as `X`.

I think `T.pack` and `L.pack` are historical and inconsistent, and like you say for myself and newbies they are arbitrary. 

However, there is resistance in our team because a lot of people don't use editor-supported things. For example, typing out `ByteString` is a pain in the arse when you could just write `S`. Your editor could let you write `bs.` and it would expand to `ByteString.` and other qualification-aware things. But if you want to appeal to people working on editors that basically aren't Vim or Emacs, then that kind of limits things.

In the wider debate of language design and whether it should assume editor tooling, I lean towards tooling rather than the bare-bones "assume only a text editor". Haskell largely is bias towards the bare-bones assumption (making simple tooling generally an uphill struggle).

**Comment by Gabriel439** [comment]
Note that I use a bare-bones `vim` for my development and type out the fully qualified module names and I still think it's a worthwhile tradeoff.  My proposal doesn't assume editor support.

**Comment by chrisdone** [comment]
@Gabriel439 Sure; I think you are probably an exception to the rule in this particular behavior, correct me if I'm wrong.

**Comment by tejon** [comment]
FWIW, plenty of editors that aren't Vim or Emacs have effective module name completion too, usually in the Intellisense style. Which, incidentally, informs my own preference for suffix adjectives; I can e.g. type `B` and get both `ByteString` and ByteStringLazy`, which reminds me to think about which one I want.

I must admit I enjoy the cleanliness of single-character imports, but if Rio is going to establish standards, I think the argument for more verbose qualification is pretty strong. And honestly, if we're going that way, `RIO.` is only four extra characters. Full qualification might not be so bad.

**Comment by snoyberg** [comment]
Like we did for another naming discussion, I've started a Twitter poll to get some feedback here: https://twitter.com/snoyberg/status/961841174121136131

**Comment by DanBurton** [comment]
My preference is usually for the qualified import to match the unqualified name of the data type that the module typically acts upon. In cases where this is ambiguous (strict vs lazy Text), I prefer having type synonyms that are not ambiguous (like LazyText) and module imports to match.

**Comment by tejon** [comment]
Parallel to the question of what qualified names to suggest: we should probably make a decision, and an explicit recommendation, on whether or not to separately import infix operators unqualified. (Assuming we have any in the qualified modules? I haven't actually checked...)

**Comment by snoyberg** [comment]
I don't believe we have any commonly used operators in those modules (though I could be mistaken). The only one that pops to mind is `!`, but that's partial and should be hidden anyway. (And I just realized that there _is_ `!?`...)

Anyway: I'm in favor of recommending unqualified import of such operators if they don't conflict with other common operators.

**Comment by tejon** [comment]
> I'm in favor of recommending unqualified import of such operators if they don't conflict with other common operators.

+1

**Comment by tejon** [comment]
I assume we _don't_ want to extend this to type names, e.g. `B.ByteString` and `BL.ByteString` should always be explicit?

**Comment by snoyberg** [comment]
Currently, the main `RIO` module exports strict `ByteString` and `Text`, provides `LByteString` and `LText` for the lazy variants, uses `Vector` for boxed vectors, and `SVector` and `UVector` for storable and unboxed, respectively. I've already been using this approach for a while in classy-prelude, and it works out nicely. I think requiring qualified imports just to refer to the data type adds too much friction, and we should be primarily encouraging the strict variants.

**Comment by snoyberg** [comment]
One more poll, on Map and Set module names. I have no horse in this race https://twitter.com/snoyberg/status/970974537620901889.

**Comment by tejon** [comment]
`M.Hash` was my horse but doesn't really fit the accepted direction of maximal abbreviation. I do still favor MH over HM tho (and TL, BL, etc.), for the search-refinement reasons I mentioned upthread.

**Comment by PierreR** [comment]
Talking about the  code readability property  (as it matters much more than the comfort of the code writer), I honestly wonder why single letter in import is something we should be aiming for ?

I would love to read more about this maybe in a blog, ...  Thanks for the standardization effort !

**Comment by snoyberg** [comment]
Alright, based on the feedback here and on Twitter, I've put together https://github.com/commercialhaskell/rio/pull/56, which I think is the closest we'll be able to get to a plurality.
