### ISSUE TITLE
Re-export readInt, readInteger in Data.ByteString.Char8

### ISSUE THREAD

**Issue by waddlaw** [commercialhaskell/rio#130]
[readInt](https://www.stackage.org/haddock/lts-12.7/bytestring-0.10.8.2/Data-ByteString-Char8.html#v:readInt) and [readInteger](https://www.stackage.org/haddock/lts-12.7/bytestring-0.10.8.2/Data-ByteString-Char8.html#v:readInteger) is defined [Data.ByteString.Char8](Data.ByteString.Char8) module in the `bytestring` package.

I think re-export these functions that it would be better. Because, `ByteString -> Int` conversion is very tedious process. If `Text -> Int`, it's very simple. use `unpack :: Text -> String`.

However, `B.unpack :: ByteString -> [Word8]` is not `String` but `Word8`.

**Comment by snoyberg** [comment]
Sorry for the delayed response. So far, we don't have any `.Char8`-style module. If we had one, I'd be in favor of including these functions. But overall, I'd rather avoid adding such a module, since the general approach of `.Char8` is error-prone.

**Comment by waddlaw** [comment]
That make sense. Understood, thank you.
