### ISSUE TITLE
Logger produces bad output on Windows

### ISSUE THREAD

**Issue by NightRa** [commercialhaskell/rio#131]
Hi there.
The RIO logger, used in stack, produces bad output on windows cmd, which doesn't support the bash escape sequences.
![winconsole](https://user-images.githubusercontent.com/2140983/44945385-f5a83d00-adf0-11e8-8047-d9d24ec78254.PNG)
In `Logger.replaceUnicode`, 
```haskell
simpleLogFunc lo cs _src level msg =
    when (level >= logMinLevel lo) $ do
      timestamp <- getTimestamp
      logSend lo $ getUtf8Builder $
        timestamp <>
        getLevel <>
        ansi reset <>
        msg <>
        getLoc <>
        ansi reset <>
        "\n"
  where
   reset = "\ESC[0m"
   setBlack = "\ESC[90m"
   setGreen = "\ESC[32m"
   setBlue = "\ESC[34m"
   setYellow = "\ESC[33m"
   setRed = "\ESC[31m"
   setMagenta = "\ESC[35m"
```
The function just outputs the reset sequences unconditionally.

RIO (and transitively stack) should instead use a platform independent console library such as `ansi-terminal`

**Comment by snoyberg** [comment]
Stack has its own workaround for this already. There are no plans to add
additional dependencies like ansi-terminal to rio. Instead, we should
default to disabling color on Windows.

**Comment by rkoeninger** [comment]
I think the relevant line of code is here:

https://github.com/commercialhaskell/rio/blob/5bf1d5e9e94526a043725d90d88323a86ce9f661/rio/src/RIO/Prelude/Logger.hs#L318

It should default to `verbose && terminal && not windows`.  I can make a PR for this and try it since I'm on Windows.
