### ISSUE TITLE
Replacing filepath and directory with path and path-io

### ISSUE THREAD

**Issue by pythonissam** [commercialhaskell/rio#132]
[filepath](https://www.stackage.org/lts-12.9/package/filepath-1.4.2) -> [path](https://www.stackage.org/lts-12.9/package/path-0.6.1)
[directory](https://www.stackage.org/lts-12.9/package/directory-1.3.1.5) -> [path-io](https://www.stackage.org/lts-12.9/package/path-io-1.3.3)

Any thoughts?

**Comment by snoyberg** [comment]
I like it in theory. However, two concerns that will block this:

* rio is following "best practices" libraries, and filepath and directory are still considered the more standard libraries for these activities.
* There are some use cases for which you still need unstructured raw file paths, such as initially accepting user input. Even the Stack codebase, where path originated, we still regularly need to use filepath/directory.

**Comment by pythonissam** [comment]
I got it. I'm sorry, but it can't be helped. Thank you.
