### ISSUE TITLE
Consider additional warning recommendations

### ISSUE THREAD

**Issue by jkachmar** [commercialhaskell/rio#135]
Max Tagher (@maxgabriel) wrote up an extremely informative overview of the various GHC warnings one can enable [here](https://medium.com/mercury-bank/enable-all-the-warnings-a0517bc081c3).

In particular, it pointed out `-Wpartial-fields`, which I hadn't been aware of but seems to be a good default.

Most of the other stuff seems fairly opinionated, but `-Widentities` would probably be a harmless addition to help avoid pointless numeric conversions.

**Comment by MaxGabriel** [comment]
Adding `-Widentities` seems like a good idea to me!

**Comment by snoyberg** [comment]
I'd be in favor of adding some of these. Does one of you want to PR the docs?

**Comment by jkachmar** [comment]
Looks like this has been addressed, I’ll close the issue.
