### ISSUE TITLE
Incorrect `Ord a` restriction on `RIO.List.maximumByMaybe`?

### ISSUE THREAD

**Issue by sgronblo** [commercialhaskell/rio#140]
http://hackage.haskell.org/package/rio-0.1.6.0/docs/RIO-List.html#v:maximumByMaybe

This restriction seems unnecessary to me. It should be enough as long as I provide `a -> a -> Ordering` to the `maximumByMaybe` shouldn't it?

This restriction is also not in `Data.List.maximumBy` as can be seen here: http://hackage.haskell.org/package/base-4.12.0.0/docs/Data-List.html#v:minimumBy

**Comment by snoyberg** [comment]
Makes sense, want to send a PR to fix this?
