### ISSUE TITLE
Extra function `displayText` added to Display

### ISSUE THREAD

**Issue by lehins** [commercialhaskell/rio#144]
I've noticed a common pattern of defining `Display` instance through `Text`, e.g. `display = display . toText`. It seems to me like `displayText` would be a nice addition to the class:

```haskell
class Display a where
  {-# MINIMAL display | displayText #-}
  display :: a -> Utf8Builder
  display = display . displayText
  displayText :: a -> Text
  displayText = utf8BuilderToText . display
```
This would allow this nice class to be useful not only for logging but also as a better alternative to `Show` as well as provide a concise implementation for `Show` instance: `show = unpack . displayText`. Most importantly, in common cases, instance declarations would be shorter, since many conversions are already available for `Text`.

Any thoughts on this? Would it be a sensible addition?

**Comment by snoyberg** [comment]
Overall +1, though I'm a bit concerned about the naming. We already have `displayShow`, which means "display based on a Show instance" instead of "display to a Show." How about `displayToText`?

**Comment by lehins** [comment]
Now that you brought up `displayShow` I do share your concern. At the same time though, `displayToText` might suggest that it converts `display` to `Text`, which isn't necessarily true, since it can be used to define `Display` instance. @snoyberg, maybe something like `textDisplay` would be clearer?

Either name we choose, I can add this to `rio`.

**Comment by snoyberg** [comment]
I'm cool with `textDisplay`, I'm _definitely_ not married to `displayToText`.
