### ISSUE TITLE
Add a `ToFilePath` typeclass of some sort?

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/rio#15]
Not a fully formed idea, but basically: define

```haskell
class ToFilePath path where
  toFilePath :: path -> FilePath
instance Char ~ a => ToFilePath  [a] where
  toFilePath = id
```

Then functions like `writeFile` can work on this typeclass instead of just `FilePath`, making it easier to start using alternatives (like @chrisdone's `path` package). Downsides:

* The dep tree to avoid orphan instances is unclear
* It breaks type inference for string literals if OverloadedStrings is turned on, e.g. `writeFile "foo.txt" "bar"`
* This doesn't fit in perfectly with matching existing best practices

**Comment by roman** [comment]
> It breaks type inference for string literals if OverloadedStrings is turned on, e.g. writeFile "foo.txt" "bar"

I believe this point is a deal breaker for me :-(...

**Comment by mgsloan** [comment]
I'd like to avoid usage much usage of `String` where possible in new abstractions like this.  Unfortunately OSes and file systems deviate wildly on encoding.  Unixes treat it as `Bytestring` for the most part, probably disallowing `\0`.  Seems like windows treats it as UTF-16 so `Text` would be a good match.

**Comment by snoyberg** [comment]
Sticking with the unopinionated and existing best practices, I don't see a good patch forward on this for now. We can reconsider in the future, but closing.
