### ISSUE TITLE
RIO.NonEmpty ?

### ISSUE THREAD

**Issue by tejon** [commercialhaskell/rio#168]
`Data.List.NonEmpty` needs a qualified import. Might be worth moving it under `RIO` to standardize the recommended qualification (and encourage its use, maybe).

**Comment by snoyberg** [comment]
Addressed by #173

**Comment by tejon** [comment]
Reopening because #173 failed to export `NonEmpty` from `RIO.Prelude`, which it probably should.

**Comment by tejon** [comment]
Addressed by #173 and #174.
