### ISSUE TITLE
Silent LogLevel

### ISSUE THREAD

**Issue by karamellpelle** [commercialhaskell/rio#184]
Shouldn't there be a function`setLogSilent :: LogOptions -> LogOptions` to use on the `LogOptions` data? Because sometimes a (command line) program shouldn't produce output when run through a bash script, for example.

**Comment by snoyberg** [comment]
In such a case, you can use `mempty` as the `LogFunc`.

**Comment by karamellpelle** [comment]
Yes, but I thought `setLogSilent :: LogOptions -> LogOptions` could be more consistent with the existing functions `setLogMinLevel` and `logSetVerboseFormat`. _rio_ already exposes a `noLogging :: (HasLogFunc env, MonadReader env m) => m a -> m a` function.

This is just a suggestion. I do not have a strong opinion about this.
