### ISSUE TITLE
ImplicitParams

### ISSUE THREAD

**Issue by int-index** [commercialhaskell/rio#19]
> `ImplicitParams` is selected so that `HasCallStack` can be used for better error messages

`ImplicitParams` are not needed to use the `HasCallStack` feature.

**Comment by snoyberg** [comment]
Does that mean that, without `ImplicitParams` on, I can add the
`HasCallStack` constraint and it will appear in call stacks?

**Comment by int-index** [comment]
Yes, the documentation states it clearly:

> NOTE: The intrepid user may notice that `HasCallStack` is just an alias for an implicit parameter `?callStack :: CallStack`. This is an implementation detail and should not be considered part of the CallStack API, we may decide to change the implementation in the future.

I've tested it in GHCi and callstacks work without `ImplicitParams` enabled.

**Comment by snoyberg** [comment]
Nice, then I'll remove that as a recommended language extension. Or if you
want to get the authorship, PR very welcome 😃
