### ISSUE TITLE
import qualified RIO.Text as Text

### ISSUE THREAD

**Issue by karamellpelle** [commercialhaskell/rio#193]
The module documentation for [RIO.Text.Partial](https://hackage.haskell.org/package/rio-0.1.10.0/docs/RIO-Text-Partial.html) says `import qualified RIO.Text.Partial as T'`, but [RIO.Text](https://hackage.haskell.org/package/rio-0.1.10.0/docs/RIO-Text.html) says `import qualified RIO.Text as Text`. Your tutorial [https://haskell.fpcomplete.com/tutorial/string-types](https://haskell.fpcomplete.com/tutorial/string-types) says `import qualified Data.Text as T`. Shouldn't RIO.Text say T? 

**PS:** Shouldn't also RIO include and export the Data.Text.IO module which has file reading/writing functionality? The RIO.ByteString exposes file reading/writing.

**Comment by snoyberg** [comment]
It would be using T everywhere, would you be interested in sending a PR to fix the docs?

Exclusion of textual IO operations is intentional. See https://www.snoyman.com/blog/2016/12/beware-of-readfile

**Comment by karamellpelle** [comment]
Thanks!
