### ISSUE TITLE
Be able to add extra context information to logging

### ISSUE THREAD

**Issue by RaoulHC** [commercialhaskell/rio#197]
It would be good to be able to add extra project specific information to log functions, to add context information automatically. For example, in a current project I'm working on, I have several threads open to manage network connections and it would be good to add which address a log message is referring to.  Currently a lot of the methods to access these parts of a `LogFunc` are private, making it hard to customise as much as I'd like in a project.

I think this could be implemented by adding a method to format the `Utf8Builder` by either:
* Transforming `unLogFunc` to format the message sent.  This would just change the message that's sent to `logGeneric`. This does mean to use with `withLogFunc` you'd need to transform it before embedding it in the monad.
* Add an optional method to `LogOptions` that formats the `Utf8Builder`, which `logGeneric` could call on the message first, before calling the actual log function. Could be `logFormat :: !(Maybe (Utf8Builder -> Utf8Builder))`

Let me know if you think any of these are a good idea (or if I'm missing some other way of going about this!) and I'll have a go at getting a PR up.

**Comment by tejon** [comment]
No reason for the `Maybe` in option 2; `id` can be used to skip formatting.

**Comment by snoyberg** [comment]
I'm OK with this change if you'd like to open a PR.

At some point, someone who's enthusiastic about logging should probably take a holistic look at rio's logging system and propose wider-ranging improvements. But this seems like a reasonable extension.

**Comment by RaoulHC** [comment]
> At some point, someone who's enthusiastic about logging should probably take a holistic look at rio's logging system and propose wider-ranging improvements. But this seems like a reasonable extension.

I wonder if it'd be worth moving some of the methods over to an internal logging module too, at the moment it feels like some of the inflexibility is from not being able to access some of the internal methods. For example having access to the `LogFunc` data constructor would make it a lot easier to pass in custom log functions.
