### ISSUE TITLE
What is the recommended way of list indexing?

### ISSUE THREAD

**Issue by jeiea** [commercialhaskell/rio#202]
I searched something like `(!!) :: [a] -> Int -> Maybe a` but couldn't find one. So I leave this question.

**Comment by snoyberg** [comment]
The RIO.List module provides a few different [list indexing functions](https://www.stackage.org/haddock/nightly-2019-11-11/rio-0.1.12.0/RIO-List.html#g:16) which are total. RIO.List.Partial provides the partial (and not recommended) [`!!`](https://www.stackage.org/haddock/nightly-2019-11-11/rio-0.1.12.0/RIO-List-Partial.html#v:-33--33-) operator.

**Comment by jeiea** [comment]
Could not `(!!)` be total for compatibility? Then I have to define one myself or use partial `(!!)`. Thanks for quick reply.

**Comment by snoyberg** [comment]
`!!` cannot be total. What would the result of `[] !! 4` be?

**Comment by jeiea** [comment]
Nothing?
I just wanted to receive `Maybe` type.

**Comment by snoyberg** [comment]
We try to match function and operator names and signatures from base, which
is where the current setup comes from.
