### ISSUE TITLE
Crash when using log func with no attached console on windows

### ISSUE THREAD

**Issue by jeiea** [commercialhaskell/rio#207]
Following snippets are not accurate, just for description.
```yaml
# package.yaml ...
ghc-options:
  - -optl-Wl,--subsystem,windows
```
```haskell
-- Main.hs
main = do
  logOptions <- logOptionsHandle stderr False
  withLogFunc logOptions $ \lf -> do
      let app = App { logFunc = lf }
      runRIO app eventLoop
```

![image](https://user-images.githubusercontent.com/4188984/72678672-83222500-3aeb-11ea-9416-c18e3d5d5abf.png)

If there was console window, no error appeared. How about disable log in this situation? It's consistent with Prelude behavior.

**Comment by snoyberg** [comment]
It seems to me like the current behavior is preferable. I'd rather an error occur than logs silently going missing. In a situation like this, you can set `mempty` as the log function to explicitly turn it into a noop.
