### ISSUE TITLE
Should Stack's Runner data type be moved into rio?

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/rio#22]

**Comment by roman** [comment]
Can you provide a link to the Runner module in the stack codebase to investigate it's purpose?

**Comment by mgsloan** [comment]
Would probably leave out stuff like `runnerReExec` and `runnerParsedCabalFiles`.  Then, it'd just turn into a way to do fancy logging with sticky lines.  I think it'd make sense to have a library related to rio that collects stuff that are specific to CLI applications.

**Comment by snoyberg** [comment]
The `Runner` type is available at https://github.com/commercialhaskell/stack/blob/e2c09ebc7120923170adf4df105b325a160b255a/src/Stack/Types/Runner.hs#L37. It may be that, with the logger type already present in rio, we just need to add a few extra fields like terminal width.

**Comment by roman** [comment]
I'm wondering if this ticket should be merged with #5, as in, it looks this is the response we want to have to Console IO? or I'm way of understanding the point of Runner?

**Comment by snoyberg** [comment]
Yes, I agree, there's no need to have a separate discussion of this now.
