### ISSUE TITLE
Lightweight Checked Exceptions

### ISSUE THREAD

**Issue by FongHou** [commercialhaskell/rio#23]
Would you consider porting/including this in RIO (RIO has a MonadThrow constraint, but uses MonadUnliftIO instead of MonadCatch/MonadMask for lifting control operations)?

https://hackage.haskell.org/package/safe-exceptions-checked-0.1.0/docs/Control-Exception-Safe-Checked.html

I found this (optional) Checked Exception capability is helpful for modeling  "application domain specific exceptions" (while leaving library/system exceptions unchecked).

Thanks!

**Comment by snoyberg** [comment]
I don't believe that approach has worked at well in practice, and goes against the exception handling best practices rio is recommending.

**Comment by roman** [comment]
Should we close this as won't implement?

**Comment by snoyberg** [comment]
Yes, good call.
