### ISSUE TITLE
Image in `README.md` broken

### ISSUE THREAD

**Issue by xtendo-org** [commercialhaskell/rio#253]
The `README.md` file ([current latest](https://github.com/commercialhaskell/rio/blob/860a4c0705e77c4734cc01bd0e34f2ce0d61f746/rio/README.md)) of _Rio_ (as in library) has long been featuring a magnificent photograph of _Rio_ (as in geography).

The corresponding part in the file is:

```markdown
![Rio](https://camo.githubusercontent.com/fc162fb0024699c85f00eae769085a5fe528153e/68747470733a2f2f7777772e61687374617469632e636f6d2f70686f746f732f636974792f76692d76363837315f30305f31343030783434322e6a7067)
```

However, [the image URL](https://camo.githubusercontent.com/fc162fb0024699c85f00eae769085a5fe528153e/68747470733a2f2f7777772e61687374617469632e636f6d2f70686f746f732f636974792f76692d76363837315f30305f31343030783434322e6a7067) no longer seems to work, returning 403:

```
$ curl -i 'https://camo.githubusercontent.com/fc162fb0024699c85f00eae769085a5fe528153e/68747470733a2f2f7777772e61687374617469632e636f6d2f70686f746f732f636974792f76692d76363837315f30305f31343030783434322e6a7067'
HTTP/2 403
cache-control: no-cache, no-store, private, must-revalidate
content-security-policy: default-src 'none'; img-src data:; style-src 'unsafe-inline'
content-type: text/plain; charset=utf-8
server: github-camo (c011ae9a)
strict-transport-security: max-age=31536000; includeSubDomains
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
x-github-request-id: 50D2:311F16:1DD83E:31B04E:66B31B59
accept-ranges: bytes
date: Wed, 07 Aug 2024 06:59:39 GMT
via: 1.1 varnish
x-served-by: cache-icn1450060-ICN
x-cache: MISS
x-cache-hits: 0
x-timer: S1723013979.160452,VS0,VE313
x-fastly-request-id: de46fd33ec8021fc5939a6c1c13804df12465447
timing-allow-origin: https://github.com
content-length: 14

Bad Signature
```

I'm not saying a fancy picture is necessary; But it seems the dead link is unintentional, so we can either remove it or fix it and restore the full glory. At least I liked the idea of introducing a well-organized software with a beautiful waterfront city of the same name. :sweat_smile:

**Comment by snoyberg** [comment]
Would be great to have it back, PR welcome.

**Comment by xtendo-org** [comment]
OK, let's see if adding an attachment here yields a usable URL hosted by GitHub's CDN.

![68747470733a2f2f7777772e61687374617469632e636f6d2f70686f746f732f636974792f76692d76363837315f30305f31343030783434322e6a7067](https://github.com/user-attachments/assets/20e95e85-0124-47ad-98ea-c211e9114b9b)
