### ISSUE TITLE
RIO.Text.removeSuffix / RIO.Text.removePrefix / RIO.List.stripSuffix

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/rio#27]
I noticed `stripCR` in the prelude and thought it was rather specific.  I'd prefer removing it and instead having the following in RIO.Text:

```haskell
removeSuffix s t = fromMaybe t (stripSuffix s t) 
```

Then `stripCR` is just `removeSuffix "\r"`.

I also often have wanted:

```haskell
stripSuffix :: [a] -> [a] -> Maybe [a]
stripSuffix s x = fmap reverse . stripPrefix (reverse s) . reverse
```

I suppose it doesn't exist because it's real inefficient.  Should it be added with a warning about efficiency?

A bit off topic:  I was surprised to see that there is no RULES pragma in base for `reverse (reverse x) = x`.

**Comment by snoyberg** [comment]
Relevant issue from mono-traversable: https://github.com/snoyberg/mono-traversable/pull/155.

**Comment by mgsloan** [comment]
Oh I like `drop` better, nice!
