### ISSUE TITLE
Prefer () / Void when appropriate?

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/rio#28]
Currently, `forever :: Applicative f => f a -> f b`, however I think a better type might be `forever :: Applicative f => f () -> f Void`.  Why is this better?

1. The typechecker will let the user know that they are ignoring the result value of the argument to forever.

2. The typechecker lets you know that it will never return.  Instead of "Sure, I'll return an Int!"

This can be recognized fairly mechanistically, I think.  Getting real formal on y'all:

* Covariant type variables that are only used once and have no constraints are isomorphic to `()`.

* Contravariant type variables that are only used once and have no constraints are isomorphic to `Void`.

For type variables like these, I think the better choice is usually to go with the concrete type.

Some reasons not to do this:

1. Making it a bit harder to port things to rio.
2. `Void` and `absurd` are potentially confusing to newcomers, because `void` in many languages is closer in meaning to `()`.  It's also weird that we also have `void :: Functor f => f a -> f ()`...

**Comment by snoyberg** [comment]
A weak -1 from me. I agree with you in principle, and would be happy if these were the types in base. My weak -1 is because this breaks the principle of rio being a collection of preexisting practices.

**Comment by mgsloan** [comment]
Hmm, perhaps time to create the more opinionated `janeiro` layer atop `rio`!

**Comment by snoyberg** [comment]
Actually, classy-prelude was already my more opinionated version :) And the plan is to make it sit on top of `rio`.

**Comment by snoyberg** [comment]
I don't think there's anything left to do here, closing.
