### ISSUE TITLE
Prelude replacement ?

### ISSUE THREAD

**Issue by flip111** [commercialhaskell/rio#32]
[haskell-foundation](https://github.com/haskell-foundation/foundation) looks pretty good. How does rio compare to foundation? Rio is offering another prelude, no?

**Comment by snoyberg** [comment]
`foundation` replaces functionality from existing libraries like text, bytestring, and vector. There are really good reasons for foundation's decision on that front, but it hurts the adoption story. rio embraces existing well used libraries instead. That's by far the biggest difference between the two libraries.

**Comment by mgsloan** [comment]
I really like both projects and want to see both succeed.  `rio` is more incrementalist / evolutionary whereas `foundation` is more revolutionary.  I have written some ideas [here](https://github.com/haskell-foundation/foundation/issues/453) about one potential approach for allowing a bit more incremental adoption of foundation.  Still a bit like "flipping a switch", but a switch that hopefully wouldn't allow any changes to the code of your dependencies.

**Comment by flip111** [comment]
Alright so one big difference is that foundation is not backwards compatible and rio is ..
It looks like rio is offering some additional things next to a prelude replacement. Would it be possible to use these additional things with the foundation prelude? Or does everything in rio integrate with each other?

**Comment by mgsloan** [comment]
There was some discussion that foundation would depend on rio and perhaps re-export much of it. At the time it sounded likely to happen.

**Comment by snoyberg** [comment]
They're mostly parallel efforts. RIO is intended to work with existing libraries. Foundation is intended to replace and improve upon existing libraries.

**Comment by snoyberg** [comment]
I don't think there's anything left to address on this issue, closing.
