### ISSUE TITLE
Namespace conflicts between RIO and RIO.Map

### ISSUE THREAD

**Issue by tejon** [commercialhaskell/rio#35]
`RIO` exports `Data.Foldable.null`. `RIO.Map` (implicitly) exports `Data.Map.Strict.null`. Being not technically the same function (despite the former being defined as the latter), they conflict. There are quite a few other examples of this (e.g. most of `Foldable`) -- `null` is just the first one I ran into.

This comes down to base `Data.Map` being intended for qualified import, so they didn't use unique names; whereas Rio doesn't suggest a default qualifier, so I assume it's intended for use without one. On the upside, the fix should be simply hiding the conflicts in `RIO.Map`'s import.

**Comment by snoyberg** [comment]
The only reason it didn't recommend a qualified name is that I having
written that documentation yet, but it's definitely intended to be
qualified. PR welcome if you'd like to add the missing comment.

**Comment by tejon** [comment]
D'oh! What I get for assuming. I can take care of that. Does this apply to everything that would be qualified under standard Prelude? At the moment it looks like only `RIO.ByteString` has a canonical qualifier.

**Comment by snoyberg** [comment]
PRs are definitely welcome. However, for the moment, there's a bit of a debate about the correct naming, see #12. I'd say that, for now, _any_ kind of recommended naming is fine, and when #12 is resolved we can update the recommendations.

**Comment by snoyberg** [comment]
Addressed by #36, closing.
