### ISSUE TITLE
Consider adding RIO.Char

### ISSUE THREAD

**Issue by tejon** [commercialhaskell/rio#37]
Simply to allow prescribing a qualified import, as Data.Char has several conflicts with Data.Text.

There's an argument that since everything else is qualified. Char doesn't have to be; but it seems better to be explicit. If I just see `toUpper`, I have to go to the imports list to really be sure I haven't simply forgotten to qualify Text. `C.toUpper` is unambiguous.

**Comment by snoyberg** [comment]
I'm in favor, want to send a PR?

**Comment by tejon** [comment]
Spaced on this until I saw you tree update, sorry!

**Comment by snoyberg** [comment]
Addressed by #41, thanks!
