### ISSUE TITLE
Will RIO include visualisation library?

### ISSUE THREAD

**Issue by AnthonyJacob** [commercialhaskell/rio#45]
When prototyping I often want to reach for quick and easy visualization. There are areas where visualization is strictly better than ascii output and then there are areas where good visualization is irreplaceable.

Are there any plans on including some lightweight, simple plotting and/or drawing library in RIO?

**Comment by snoyberg** [comment]
I had no plans on including it in the main `rio` library: there are no established best practices, and while a need many people have, I don't think it rises to the same level of commonality such that the majority of applications need some version of it. Like testing and command line parsing (see #7 and #11), I think it would be a good candidate for a sibling package.
