### ISSUE TITLE
Recommended flags?

### ISSUE THREAD

**Issue by bonds** [commercialhaskell/rio#46]
[This article](https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/) got me wondering what y'all think of:

- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

possibly in the (future) template, in the package.yaml.

**Comment by snoyberg** [comment]
I think this is a great idea for a future template. Do you want to send a PR to the `README.md` to add a section for recommended flags?

**Comment by bonds** [comment]
Here you go: https://github.com/commercialhaskell/rio/pull/47

**Comment by snoyberg** [comment]
Addressed by #47, thanks!
