### ISSUE TITLE
Include Data.Sequence to RIO structure modules?

### ISSUE THREAD

**Issue by roman** [commercialhaskell/rio#57]
Hello,

Wondering why there is no RIO export for `Data.Sequence`, is there a reason why is this the case?

**Comment by snoyberg** [comment]
I can't think of a reason to exclude it, I'd be in favor of a PR to add it.

**Comment by roman** [comment]
I've always wondered why the module name was `Sequence` and the data structure was `Seq`, what do you think about naming the module `RIO.Seq` instead of `RIO.Sequence`?

**Comment by snoyberg** [comment]
Thanks!
