### ISSUE TITLE
Add module RIO.STM and RIO.Concurrent?

### ISSUE THREAD

**Issue by roman** [commercialhaskell/rio#64]
I've noticed some of the `Control.Concurrent.STM` symbols are already given in `RIO`, however, others are missing (e.g. `retry`). 

As well as STM, `RIO` does not export `myThreadId` nor `threadDelay`, should we provide explicit modules for those, or just include them as re-exports in RIO?

**Comment by snoyberg** [comment]
The modules are supposed to be handled via UnliftIO right now. If there are missing components, can you open a PR there? For retry, I think it's called retrySTM to avoid name clashes, but I'm not sure that's necessary.
