### ISSUE TITLE
Move / expose some RIO.Prelude.* modules

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/rio#71]
In PR #72, I propose to not export all the modules under `RIO.Prelude.*`.  However, in some cases you might not want to import `RIO`, yet you still want to use some stuff from it without import lists.  I'm thinking the following are good candidates for renaming and inclusion in `exposed-modules`:

* `RIO.Prelude.Display` -> `RIO.Display`
* `RIO.Prelude.Logger` -> `RIO.Logger`
* `RIO.Prelude.RIO` -> `RIO.Monad`?  Iffy.  `RIO.RIO` seems a little overexcited about RIO.
* `RIO.Prelude.Trace` -> `RIO.Trace` 
* `RIO.Prelude.URef` -> `RIO.URef`?  Also a bit iffy since there isn't a `RIO.IORef`, for example.

So, this would leave the following modules under `RIO.Prelude.___`, and not included in `exposed-modules`: `Extra`, `IO`, `Lens`, `Reexports`, `Renames`, and `Text`.

**Comment by snoyberg** [comment]
This makes the module structure confusing. Until now, if something is in `RIO.*`, it's _not_ exposed by `RIO` itself. This will change around that assumption.

**Comment by snoyberg** [comment]
I thought about this more. Doing the move should be fine, we just need to include a comment in the module header "this is exported by `RIO`" or similar.

**Comment by jkachmar** [comment]
It looks as if this issue was addressed in b23f9c5, can it be closed?

**Comment by ketzacoatl** [comment]
I think so, but @snoyberg can re-open if there is more to do.

**Comment by snoyberg** [comment]
Yeah, let's close, thanks @ketzacoatl.
