### ISSUE TITLE
Consider deprecating "stdin" / "stdout" / "stderr" in favor of "askStdin" / "askStdout" / "askStderr"

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/rio#77]
One minor gripe I have with the `System.IO` API (and, by extension, `UnliftIO.IO`) is the existence of global handles for stdio.  In some circumstances it'd be quite handy if these were overridable with a bracketlike function such as `withStdin h f`.  This would allow for silencing or redirecting output from a subpart of the program.

Perhaps this sort of silencing / redirecting / filtering / reformatting is the domain of `RIO.Prelude.Logger`. 
 However, that doesn't really handle overriding stdin.  I think it would be nice if it was recommended to instead use `askStdin :: (MonadReader env m, HasStdio env) -> m Handle`.  So, RIO might still export `stdin`, but with a deprecation pragma saying to prefer `askStdin`.

Not really sure if this is worth it, because it would mean that everyone would need to have stdio handles in their reader environment.  It would not be possible to fallback on `stdin` / `stdout` / etc, because `HasStdio` would provide lenses on the environment so that they can be modified locally.

After typing this up, I've realized that it does not really pass the test of "codifying existing common practice".  However, this sort of layer is the place to address this if we want to have any hope of having the ability to locally override stdio.

**Comment by tejon** [comment]
> Not really sure if this is worth it, because it would mean that everyone would need to have stdio handles in their reader environment.

Hm. We could provide a StdHandles type and smart constructor, which would at least streamline this.

We... _could_... bake that into RIO, making it secretly `ReaderT env (ReaderT StdHandles IO)`.

The latter idea is almost certainly horrifically terrible. Unless we newtype it as `StdRIO` so it's optional. Then just regular terrible?

**Comment by snoyberg** [comment]
Personally, I think this is too far into the "not common practice" area, at least for now.

**Comment by mgsloan** [comment]
Yup, reasonable!
