### ISSUE TITLE
Offer durable file writing functions

### ISSUE THREAD

**Issue by nh2** [commercialhaskell/rio#87]
`rio` should offer file writing functions that are durable.

That involves `fsync()`ing the file itself after writing and **before** `close()`, and `fsync()`ing the directory that contains the file. It also involves failing hard on errors in `fsync()`, as retrying fsync has no effect.

Sources for fsyncing the directory:

* http://blog.httrack.com/blog/2013/11/15/everything-you-always-wanted-to-know-about-fsync/

See also:

* https://wiki.postgresql.org/wiki/Fsync_Errors ("fsyncgate")
* Mailing list entry [PostgreSQL's handling of fsync() errors is unsafe and risks data loss at least on XFS](https://www.postgresql.org/message-id/flat/CAMsr%2BYHh%2B5Oq4xziwwoEfhoTZgr07vdGG%2Bhu%3D1adXx59aTeaoQ%40mail.gmail.com#CAMsr+YHh+5Oq4xziwwoEfhoTZgr07vdGG+hu=1adXx59aTeaoQ@mail.gmail.com)
* https://stackoverflow.com/questions/42434872/writing-programs-to-cope-with-i-o-errors-causing-lost-writes-on-linux from the same author
* My question about [fsync() after close() and re-open](https://marc.info/?l=linux-fsdevel&m=152535098505449&w=2) on the `linux-fsdevel` mailing list
* My [Stackoverflow answer on this topic](https://stackoverflow.com/questions/37288453/calling-fsync2-after-close2/50158433#50158433)
* The "atomic move" pattern implemented with `rename()` [isn't enough](https://stackoverflow.com/questions/3764822/how-to-durably-rename-a-file-in-posix) to ensure durability
* [Interesting post on the Linux side of things](https://www.postgresql.org/message-id/20180427222842.in2e4mibx45zdth5@alap3.anarazel.de)

Note it [may not be possible to provide durable variants for all operating and file systems](https://stackoverflow.com/a/16500274/263061), but these functions should be as durable as they can be.

We should also discuss whether durability should be the default in `writeFileBinary` and `writeFileUtf8`.

In general, `rio` should expose durable and non-durable variants of file writing operations.

**Comment by nh2** [comment]
> We should also discuss whether durability should be the default in writeFileBinary and writeFileUtf8.

My personal take right now is safe defaults are better, even if they are much slower due to the fsyncs and moves.

And ideally the docs should point out things like "if you do not need durability, use this other function which is much faster".

Also relevant for atomic moves (and performance) is whether the source and target are on the safe file system (overwise the `rename()` is not atomic at all).

**Comment by snoyberg** [comment]
The atomic move issue is probably the biggest question mark about this for me. AFAICT, the only way to reliably implement this is to create a temporary file in the same directory as the target file and then move it. However, in the case of program crashes/SIGKILLs/etc, there's a possibility that the file could be left behind, meaning that this change doesn't just trade performance for durability, but also introduces slight externally-visible semantic changes.

**Comment by nh2** [comment]
I found another very useful thread that discusses these issues, and particular wheter `fsync()` after `rename()` is necessary (the answer there is yes):

* https://groups.google.com/forum/#!topic/comp.unix.programmer/AM2V83RCOVE

**Comment by lehins** [comment]
Just stumbled on this ticket. It seems like it can be closed, no?

**Comment by snoyberg** [comment]
I think so
