### ISSUE TITLE
Re-export System.Process.Typed functions unmodified

### ISSUE THREAD

**Issue by roman** [commercialhaskell/rio#97]
Creating `ProcessConfig` records with the functions exported from the `RIO.Process` module has a lot of friction in common scenarios. The [`RIO.Process.proc`](https://github.com/commercialhaskell/rio/blob/master/rio/src/RIO/Process.hs#L405) function expects the caller to have a Reader environment with both logging capabilities and process context capabilities. These requirements become rather awkward when trying to create a new process from an already existing reader environment that has a `LogFunc`.  Following an example with two independent modules:

### Main Module

```haskell
{-# LANGUAGE NoImplicitPrelude #-}
module Main where

import RIO
import qualified Lib

main :: IO ()
main = do
  -- main application will always have a logging function
  logOptions <- logOptionsHandle stdout False
  withLogFunc logOptions $ \logFunc -> 
    runRIO logFunc $ do 
     -- some other things before that only require logging and spawn other processes
     Lib.spawnProcess
     -- some other things after
```

### Library Module

```haskell
{-# LANGUAGE NoImplicitPrelude #-}
module Lib where

import RIO
import qualified RIO.Process as Process

spawnProcess :: (HasLogFunc env, MonadReader env m) => m ()
spawnProcess = do
  logFunc <- view logFuncL
  procCtx <- Process.mkDefaultContext
  liftIO $ runRIO (Process.LoggedProcessContext processCtx logFunc) $ do
    Process.proc "mycmd" ["arg1"] $ \procConfig ->
      -- Lots of java-esque ceremonies just to get here </3
```

It seems the `RIO.Process` module is optimized for a particular use case that is not exactly what I need. One simple solution is to add `typed-process` directly in my `package.yaml` and import `System.Process.Typed` instead, but then again, I'm using `rio` and I'm expecting to have a module that re-exports that functionality for me, the same way it does with `text`, `bytestring`, and others...

Can we rename `RIO.Process` to something more specific, like `RIO.Process.Context`, and leave `RIO.Process` to be a re-export module for `RIO.Process` instead?

Let me know your thoughts.

**Comment by snoyberg** [comment]
I'm really not in favor of this. You already have a `LogFunc` in your `App`, what's the problem with adding in a `ProcessContext` too?

**Comment by roman** [comment]
I don't mind adding a `ProcessContext`, I need to understand _why_ I would like one in the first place? :-)

**Comment by snoyberg** [comment]
That's explained in the module documentation itself, namely:

* Efficiency of lookups
* Easier working directory changes

These were important changes needed for Stack, where this concept was originally developed. It doesn't hurt the normal use case, besides adding an extra value to the environment, which is explicitly something rio isn't afraid to do.

**Comment by roman** [comment]
> It doesn't hurt the normal use case, besides adding an extra value to the environment, which is explicitly something rio isn't afraid to do.

Agreed, I have to be honest, I didn't read the documentation of `RIO.Process` because my expectation was that it was a simple re-export. I understand that the idea is to treat `ProcessContext` as `LogFunc`, something you will *always* build in your application environment.

Closing ticket.
